### ISSUE TITLE
When will it be open source?

### ISSUE THREAD

**Issue by 15514706615** [ayshrv/gmrw#1]
When will it be open source?

**Comment by ayshrv** [comment]
Hi, we will release it this week.

**Comment by CzJamesZhao** [comment]
> Hi, we will release it this week.

I really appreciate it and I'm looking forward to the release.

**Comment by eugenelawrence** [comment]
It has been a month already.

**Comment by ayshrv** [comment]
Hi all,

Sorry for the delay and thanks for the wait, the code is public now.
